version: '3'
services:
  nginx:
    image: axizdkr/tengine
    container_name: 'nginx'
    ports:
      - 80:80
      - 443:443
    expose:
      - 80
      - 443
    volumes:
      - /opt/nginx/configs/:/etc/nginx/configs/
      - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - vaultwarden
    restart: always
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: 'vaultwarden'
    environment:
     - SIGNUPS_ALLOWED=false
    volumes:
     - /opt/bitwarden/bw-data/:/data/
    restart: always
